title: The Type Hype
description: ""
header_text: ""
footer_text: Copyright 2020 Your name
header_feature_image: ../uploads/typehypebanner.png
bannerheight: 40vmax
logo: ../uploads/blue-playful-pop-of-color-food-_-drink-logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
