title: Typography in the Fashion Industry
description: ""
header_text: ""
footer_text: Copyright 2020 Beth Poppy Erskine
header_feature_image: ../uploads/type-hype-banner.png
bannerheight: 40vmax
logo: ../uploads/blue-playful-pop-of-color-food-_-drink-logo.png
favicon: ../uploads/apple-touch-icon.png
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - name: "About me "
    siteurl: file:///Users/beth/Desktop/beth.html/aboutme
